name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive # 递归拉取所有子模块
        fetch-depth: 0        # 确保完整克隆（非浅克隆）
        
    - name: Login to DockerHub
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_HUB }}
        
    - name: Build the Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB }}/${{ github.repository }}
        TAG=v$(date +%Y%m%d%H%M)
        docker build . --file Dockerfile.amd64 --tag $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$TAG
        
    - name: Create Release Notes
      id: create_release_notes
      run: |
        echo "Docker Image Released!" > release_notes.txt
        echo "Image: $IMAGE_NAME:$IMAGE_TAG" >> release_notes.txt

    - name: Upload to GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}-docker-image
        release_name: Docker Image Release for ${{ github.ref_name }}
        body_path: release_notes.txt
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
