name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_HUB }}
    - name: Build the Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB }}/${{ github.repository }}
        TAG=v$(date +%Y%m%d%H%M)
        docker build . --file Dockerfile.amd64 --tag $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$TAG
