name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive # 递归拉取所有子模块
        fetch-depth: 0        # 确保完整克隆（非浅克隆）

    - name: Set Image Variables
      run: |
        echo "IMAGE_NAME=${{ secrets.DOCKER_HUB }}/${{ github.repository }}" >> $GITHUB_ENV
        echo "IMAGE_TAG=v$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "release_date=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_HUB }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.amd64
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} 

    - name: Create Release with Notes
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.ref_name }}
        body: |
          ### Release Details
          - Date: ${{ env.release_date }}
          - Image: `${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}`
        tag_name: ${{ github.event.inputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
